export const getIpList = state => state.ipList
export const getIps = state => state.ips
export const getIpsArr = state => state.ipsArr
export const getPoi = state => state.poi
export const getTabPoiStrArr = state => state.tabPoiStrArr
export const getPoiStr = state => state.poiStr
export const getKey = state => state.key
export const getTabLocation = state => state.tabLocation
export const getLocationObj = state => state.locationObj
export const getToken = state => state.token
export const getFormData = state => state.formData
export const getPoiTypeArr = state => state.poiTypeArr
export const getCityCode = state => state.cityCode
export const getMap = state => state.map
export const getTabLocationList = state => state.tabLocationList
export const getAreaInfo = state => state.areaInfo
export const getOffObj = state => state.offObj
export const getCountryHtml = state => state.countryHtml
